{{- if .Values.appRoleSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets-manager.appRoleSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-manager.labels" . | nindent 4 }}
  {{- with .Values.appRoleSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  role_id: {{ .Values.appRoleSecret.data.roleId | b64enc | quote }}
  secret_id: {{ .Values.appRoleSecret.data.secretId | b64enc | quote }}
{{- end }}