{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secrets-manager.fullname" . }}
  labels:
    {{- include "secrets-manager.selectorLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - "secrets-manager.tuenti.io"
  resources:
  - "secrets"
  - "secretdefinitions"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
  - "delete"
  - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "secrets-manager.fullname" . }}
  labels:
    {{- include "secrets-manager.selectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "secrets-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "secrets-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}